In [1]:
import numpy as np

In [2]:
#create a list named list1
list = [2,4,6,8]
array1=np.array(list)
print(array1)

[2 4 6 8]


In [5]:
#create a 2D array with 2 rows and 4 columns
array1 = np.array([[1,2,3,4],[5,6,7,8]])
print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
#create a 3D array with 2 "slices", each of 3 rows and 4 columns
array1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20],[21,22,23,24]])
print(array1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
